[workspace]
members = [
    "monoio-server",
    "tokio-server",
    "glommio-server",
    "client",
    "config",
]
resolver = "2"

[workspace.dependencies]
monoio = { version = "0.1.9" }

[profile.release]
lto = true
debug = false
overflow-checks = false
